version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: task_manager_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: truongdeptrai
      MYSQL_DATABASE: task_management
      MYSQL_USER: root
      MYSQL_PASSWORD: truongdeptrai
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: